---
title: "Prism"
output: html_document
date: "2024-05-09"
---

```{r}
# Load required libraries
library(raster)
library(sf)
library(dplyr)
library(ggplot2)
library(plotrix)
library(ggpubr)
library(tidyr)
library(tidyverse)
library(sf)
library(plantTracker)

aea.proj <- "+proj=aea +lat_1=29.5 +lat_2=45.5 +lat_0=37.5 +lon_0=-96 +x_0=0 +y_0=0 +ellps=GRS80 +datum=NAD83 +units=m +no_defs"

ngpShape2<-st_read("~/Desktop/dust bowl/ngp_boundary_WGS/ngp_boundary_WGS.shp")
ngpShape2<-st_transform(ngpShape2, crs=aea.proj)

filepathPRISMppt<-file.path("~/Desktop/prism data/prism ppt")

dirPRISMppt<-dir(filepathPRISMppt, full.names = T,pattern= "\\.bil$" )

prismppt<-lapply(dirPRISMppt,function(dirPRISMppt){ 
  rasters<-raster(dirPRISMppt)
  rasters<- projectRaster(rasters, crs = aea.proj)
  raster2 <- mask(rasters, ngpShape2)
  raster2 <- crop(raster2, ngpShape2)
  rasterdata<-rasterToPoints(raster2)
  rasterdf<-as.data.frame(rasterdata)
  rasterdf$year<-(as.character(dirPRISMppt))
  rasterdf$year<-substr(rasterdf$year, 69,72)
  rasterdf$month<-(as.character(dirPRISMppt))
  rasterdf$month<-substr(rasterdf$month, 73,74)
  names(rasterdf)[3] <- "ppt"
  (rasterdf)
  })

prismdfppt<-bind_rows(prismppt) 


```

```{r}
prismdfppt<-prismdfppt%>%
  group_by(x,y,year)%>%
  summarise_at(vars(ppt),
              list(ppt=mean))

prismdfPPTmean<-prismdfppt%>%
  group_by(x,y)%>%
  mutate(MAP=mean(ppt))

prismdfanomalPPT<-prismdfPPTmean%>%
  mutate(anomaly=MAP-ppt)

dustbowldataPPT<-prismdfanomalPPT%>%
  filter(year<=1937&year>=1932)

dustbowlanomalyPPT<-dustbowldataPPT%>%
  group_by(x,y)%>%
  mutate(absolute=(anomaly))%>%
  mutate(relative=((ppt-MAP)/MAP*100))

mapPPTdata<-dustbowlanomalyPPT%>%
  group_by(x,y)%>%
  summarise_at(vars(absolute,relative),
               list(mean))
```


```{r}

#Create states outline data
setwd("~/OneDrive - Montana State University/rds")
us<-readRDS("gadm36_USA_1_sp.rds")
us<-getData("GADM", country='USA', level=1,download=TRUE)
states_all_sites <- us[us$NAME_1 %in% c(
                                        'Wyoming',
                                        'Montana',
                                        'North Dakota','South Dakota','Nebraska'
                                       ),]

aea.proj <- "+proj=aea +lat_1=29.5 +lat_2=45.5 +lat_0=37.5 +lon_0=-96 +x_0=0 +y_0=0 +ellps=GRS80 +datum=NAD83 +units=m +no_defs"
states_all_sites <- spTransform(states_all_sites, CRS(aea.proj))

```

```{r}
lat <- 46.22
long <- -105.53

# Create a data frame
df <- data.frame(long = long, lat = lat)

# Convert to sf object with WGS84 projection (EPSG:4326)
sf_point <- st_as_sf(df, coords = c("long", "lat"), crs = 4326)

# Transform to EPSG:3857 (Web Mercator projection)
sf_point_transformed <- st_transform(sf_point, crs = aea.proj)
coords<-as.data.frame(st_coordinates(sf_point_transformed))
```


```{r}
library(ggstar)

absolutePPT<-ggplot() + 
  geom_raster(mapPPTdata, mapping=aes(x=x,y=y,fill=absolute))+
  geom_polygon(data=states_all_sites, mapping=aes(x = long, y = lat, group=group),
              color = "black", linewidth = 0.1,fill=NA)+
  geom_point(coords, mapping=aes(x=X,y=Y),color="black", size=5,shape=18)+
  scale_fill_distiller(palette="Spectral",direction=1,limits=c(-2,2),oob=scales::squish)+
    theme(
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    axis.ticks = element_blank(),
    legend.key = element_blank(),
    legend.position = 'right',
    strip.background =element_rect(fill="white"),
    strip.text = element_text(size=10),
    panel.background = element_rect(fill=NA),
    panel.border = element_blank(), #make the borders clear in prep for just have two axes
    axis.line.x = element_blank(),
    axis.line.y = element_blank(),
    axis.text = element_blank(),
    plot.title = element_text(face="bold", hjust=.5))+
  guides(fill=guide_colourbar(barwidth=.8, barheight=6, title.hjust=0, title="Annual PPT anomaly \naveraged 1932-1937", draw.llim = TRUE, draw.ulim = TRUE,title.position="top"))
absolutePPT

relative<-ggplot() + 
  geom_raster(mapPPTdata, mapping=aes(x=x,y=y,fill=relative))+
  geom_polygon(data=states_all_sites, mapping=aes(x = long, y = lat, group=group),
               color = "black", linewidth = 0.1,fill=NA)+
  geom_point(coords, mapping=aes(x=X,y=Y),color="black", size=5,shape=18)+
  scale_fill_distiller(palette="Spectral",direction=1,limits=c(-30,30),oob=scales::squish)+
    theme(
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    axis.ticks = element_blank(),
    legend.key = element_blank(),
    legend.position = 'right',
    strip.background =element_rect(fill="white"),
    strip.text = element_text(size=10),
    panel.background = element_rect(fill=NA),
    panel.border = element_blank(), #make the borders clear in prep for just have two axes
    axis.line.x = element_blank(),
    axis.line.y = element_blank(),
    axis.text = element_blank(),
    plot.title = element_text(face="bold", hjust=.5))+
   labs(fill = "Average annual % difference \nfrom MAP (1932-1937)") +
  theme(legend.position = c(.3, .1), legend.direction = "horizontal")
relative
```

```{r}
jpeg("combined precip fig.jpeg",
     width=14,
     height=6,
     units="in",
     res=300)
ggarrange(relative,combined_plot,labels= c("(a)","(b)"),ncol=2)
dev.off
```
**Max temperature**

```{r}
filepathPRISMtemp<-file.path("~/Desktop/prism data/prism temp")

dirPRISMtemp<-dir(filepathPRISMtemp, full.names = T,pattern= "\\.bil$" )

prismtemp<-lapply(dirPRISMtemp,function(dirPRISMtemp){ 
  rasters<-raster(dirPRISMtemp)
  rasters<- projectRaster(rasters, crs = aea.proj)
  raster2 <- mask(rasters, ngpShape2)
  raster2 <- crop(raster2, ngpShape2)
  rasterdata<-rasterToPoints(raster2)
  rasterdf<-as.data.frame(rasterdata)
  rasterdf$year<-(as.character(dirPRISMtemp))
  rasterdf$year<-substr(rasterdf$year, 71,74)
  rasterdf$month<-(as.character(dirPRISMtemp))
  rasterdf$month<-substr(rasterdf$month, 75,76)
  names(rasterdf)[3] <- "temp"
  (rasterdf)
  })
prismdftemp<-bind_rows(prismtemp) 


```

```{r}
prismtempmeans<-merge(prismdftemp,prismdf2023)

prismtempmeans<-prismdftemp%>%
  group_by(x,y)%>%
  mutate(MAT=mean(temp))

prismtempmeans<-prismtempmeans%>%
  group_by(year,x,y)%>%
  mutate(annualtemp=mean(temp))

prismtempanomaly<-prismtempmeans%>%
  mutate(anomaly=annualtemp-MAT)

tempmean<-prismtempanomaly%>%
  group_by(x,y)%>%
  mutate(mean=mean(anomaly))

dustbowlTEMP<-prismtempanomaly%>%
  filter(year<=1937&year>=1932)

dustbowlTEMPanomaly<-dustbowlTEMP%>%
  group_by(x,y)%>%
  mutate(absolute=mean(anomaly))%>%
  mutate(relative=mean((temp-MAT)/MAT*100))

tempanom23<-prismtempmeans%>%
  filter(year==2023)

tempANOM<-tempanom23%>%
  group_by(x,y)%>%
  mutate(meanTEMP=mean(temp))
         
tempANOM%>%
  group_by(x,y)%>%
  mutate(absolute=anomaly)%>%
  mutate(relative=((temp-MAT)/MAT*100))

tempANO <-tempANOM%>%
  group_by(x,y)%>%
  summarise_at(vars(absolute,relative),
               list(mean=mean))



```

```{r}
library(ggstar)

absoluteTEMP<-ggplot() + 
  geom_raster(dustbowlTEMPanomaly, mapping=aes(x=x,y=y,fill=absolute))+
  geom_polygon(data=states_all_sites, mapping=aes(x = long, y = lat, group=group),
              color = "black", linewidth = 0.1,fill=NA)+
  geom_point(coords, mapping=aes(x=X,y=Y),color="black", size=5,shape=18)+
  scale_fill_distiller(palette="Spectral",direction=1,limits=c(-.5,1),oob=scales::squish)+
    theme(
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    axis.ticks = element_blank(),
    legend.key = element_blank(),
    legend.position = 'right',
    strip.background =element_rect(fill="white"),
    strip.text = element_text(size=10),
    panel.background = element_rect(fill=NA),
    panel.border = element_blank(), #make the borders clear in prep for just have two axes
    axis.line.x = element_blank(),
    axis.line.y = element_blank(),
    axis.text = element_blank(),
    plot.title = element_text(face="bold", hjust=.5))+
  guides(fill=guide_colourbar(barwidth=.8, barheight=6, title.hjust=0, title="Annual TEMP anomaly \naveraged 1932-1937", draw.llim = TRUE, draw.ulim = TRUE,title.position="top"))
absoluteTEMP


relativeTEMP<-ggplot() + 
  geom_raster(tempANOM, mapping=aes(x=x,y=y,fill=relative))+
  geom_polygon(data=states_all_sites, mapping=aes(x = long, y = lat, group=group),
               color = "black", linewidth = 0.1,fill=NA)+
  geom_point(coords, mapping=aes(x=X,y=Y),color="black", size=5,shape=18)+
  scale_fill_distiller(palette="Spectral",direction=-1,limits=c(-7,10),oob=scales::squish)+
    theme(
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    axis.ticks = element_blank(),
    legend.key = element_blank(),
    legend.position = 'right',
    strip.background =element_rect(fill="white"),
    strip.text = element_text(size=10),
    panel.background = element_rect(fill=NA),
    panel.border = element_blank(), #make the borders clear in prep for just have two axes
    axis.line.x = element_blank(),
    axis.line.y = element_blank(),
    axis.text = element_blank(),
    plot.title = element_text(face="bold", hjust=.5))+
   labs(fill = "Average annual % difference \nfrom MAT (1932-1937)") +
  theme(legend.position = c(.3, .1), legend.direction = "horizontal")
relativeTEMP
```

```{r}

filepathPRISMvpmax<-file.path("~/Desktop/prism data/prism vpmax")

dirPRISMvpmax<-dir(filepathPRISMvpmax, full.names = T,pattern= "\\.bil$" )

prismvpmax<-lapply(dirPRISMvpmax,function(dirPRISMvpmax){ 
  rasters<-raster(dirPRISMvpmax)
  rasters<- projectRaster(rasters, crs = aea.proj)
  raster2 <- mask(rasters, ngpShape2)
  raster2 <- crop(raster2, ngpShape2)
  rasterdata<-rasterToPoints(raster2)
  rasterdf<-as.data.frame(rasterdata)
  rasterdf$year<-(as.character(dirPRISMvpmax))
  rasterdf$year<-substr(rasterdf$year, 74,77)
  rasterdf$month<-(as.character(dirPRISMvpmax))
  rasterdf$month<-substr(rasterdf$month, 78,79)
  names(rasterdf)[3] <- "vpmax"
  (rasterdf)
  })

prismdfvpmax<-bind_rows(prismvpmax) 
```

```{r}
prismdfvpmax<-prismdfvpmax%>%
  group_by(x,y,year)%>%
  summarise_at(vars(vpmax),
              list(vpmax=mean))

prismdfVPmean<-prismdfvpmax%>%
  group_by(x,y)%>%
  mutate(meanVP=mean(vpmax))

prismdfanomalVP<-prismdfVPmean%>%
  mutate(anomaly=vpmax-meanVP)

dustbowldataVP<-prismdfanomalVP%>%
  filter(year<=1937&year>=1932)

dustbowlanomalyVP<-dustbowldataVP%>%
  group_by(x,y)%>%
  mutate(absolute=(anomaly))%>%
  mutate(relative=((vpmax-meanVP)/meanVP*100))

mapVPdata<-dustbowlanomalyVP%>%
  group_by(x,y)%>%
  summarise_at(vars(absolute,relative),
               list(mean))
```

```{r}
absoluteVP<-ggplot() + 
  geom_raster(mapVPdata, mapping=aes(x=x,y=y,fill=absolute))+
  geom_polygon(data=states_all_sites, mapping=aes(x = long, y = lat, group=group),
              color = "black", linewidth = 0.1,fill=NA)+
  geom_point(coords, mapping=aes(x=X,y=Y),color="black", size=5,shape=18)+
  scale_fill_distiller(palette="Spectral",direction=1,limits=c(-.3,3),oob=scales::squish)+
    theme(
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    axis.ticks = element_blank(),
    legend.key = element_blank(),
    legend.position = 'right',
    strip.background =element_rect(fill="white"),
    strip.text = element_text(size=10),
    panel.background = element_rect(fill=NA),
    panel.border = element_blank(), #make the borders clear in prep for just have two axes
    axis.line.x = element_blank(),
    axis.line.y = element_blank(),
    axis.text = element_blank(),
    plot.title = element_text(face="bold", hjust=.5))+
  guides(fill=guide_colourbar(barwidth=.8, barheight=6, title.hjust=0, title="Annual max VP anomaly \naveraged 1932-1937", draw.llim = TRUE, draw.ulim = TRUE,title.position="top"))
absoluteVP


relativeTEMP<-ggplot() + 
  geom_raster(mapVPdata, mapping=aes(x=x,y=y,fill=relative))+
  geom_polygon(data=states_all_sites, mapping=aes(x = long, y = lat, group=group),
               color = "black", linewidth = 0.1,fill=NA)+
  geom_point(coords, mapping=aes(x=X,y=Y),color="black", size=5,shape=18)+
  scale_fill_distiller(palette="Spectral",direction=-1,limits=c(-2,18),oob=scales::squish)+
    theme(
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    axis.ticks = element_blank(),
    legend.key = element_blank(),
    legend.position = 'right',
    strip.background =element_rect(fill="white"),
    strip.text = element_text(size=10),
    panel.background = element_rect(fill=NA),
    panel.border = element_blank(), #make the borders clear in prep for just have two axes
    axis.line.x = element_blank(),
    axis.line.y = element_blank(),
    axis.text = element_blank(),
    plot.title = element_text(face="bold", hjust=.5))+
   labs(fill = "Average annual % difference \nfrom mean annual VP (1932-1937)") +
  theme(legend.position = c(.3, .1), legend.direction = "horizontal")
relativeTEMP
```

